## dev环境使用是配置
server:
  port: 8084
  context-path: /

spring:
  http:
    encoding:
      force: true


  ##静态资源
resources:
  ##静态资源
  ## -- 如果不配置，都可以访问
  ## -- 如果配置，都可以只能访问指定路径下的
  ## http://localhost:8081/chao/static.txt
  ## http://localhost:8081/chao/public.txt
  static-locations: classpath:/static/,classpath:/public/







